/*
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.5
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.checkout.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tebex.checkout.model.Address;
import io.tebex.checkout.model.BasketLinks;
import io.tebex.checkout.model.BasketRow;
import io.tebex.checkout.model.Payment;
import io.tebex.checkout.model.PriceDetails;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.tebex.checkout.invoker.JSON;

/**
 * Basket
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Basket {
  public static final String SERIALIZED_NAME_IDENT = "ident";
  @SerializedName(SERIALIZED_NAME_IDENT)
  @javax.annotation.Nullable
  private String ident;

  public static final String SERIALIZED_NAME_EXPIRE = "expire";
  @SerializedName(SERIALIZED_NAME_EXPIRE)
  @javax.annotation.Nullable
  private String expire;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @javax.annotation.Nullable
  private Float price;

  public static final String SERIALIZED_NAME_PRICE_DETAILS = "priceDetails";
  @SerializedName(SERIALIZED_NAME_PRICE_DETAILS)
  @javax.annotation.Nullable
  private PriceDetails priceDetails;

  public static final String SERIALIZED_NAME_IS_PAYMENT_METHOD_UPDATE = "isPaymentMethodUpdate";
  @SerializedName(SERIALIZED_NAME_IS_PAYMENT_METHOD_UPDATE)
  @javax.annotation.Nullable
  private Boolean isPaymentMethodUpdate;

  public static final String SERIALIZED_NAME_RETURN_URL = "returnUrl";
  @SerializedName(SERIALIZED_NAME_RETURN_URL)
  @javax.annotation.Nullable
  private String returnUrl;

  public static final String SERIALIZED_NAME_COMPLETE = "complete";
  @SerializedName(SERIALIZED_NAME_COMPLETE)
  @javax.annotation.Nullable
  private Boolean complete;

  public static final String SERIALIZED_NAME_TAX = "tax";
  @SerializedName(SERIALIZED_NAME_TAX)
  @javax.annotation.Nullable
  private BigDecimal tax;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  @javax.annotation.Nullable
  private String username;

  public static final String SERIALIZED_NAME_EMAIL_IMMUTABLE = "email_immutable";
  @SerializedName(SERIALIZED_NAME_EMAIL_IMMUTABLE)
  @javax.annotation.Nullable
  private Boolean emailImmutable;

  public static final String SERIALIZED_NAME_DISCOUNTS = "discounts";
  @SerializedName(SERIALIZED_NAME_DISCOUNTS)
  @javax.annotation.Nullable
  private List<Object> discounts = new ArrayList<>();

  public static final String SERIALIZED_NAME_COUPONS = "coupons";
  @SerializedName(SERIALIZED_NAME_COUPONS)
  @javax.annotation.Nullable
  private List<Object> coupons = new ArrayList<>();

  public static final String SERIALIZED_NAME_GIFTCARDS = "giftcards";
  @SerializedName(SERIALIZED_NAME_GIFTCARDS)
  @javax.annotation.Nullable
  private List<Object> giftcards = new ArrayList<>();

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private Address address;

  public static final String SERIALIZED_NAME_ROWS = "rows";
  @SerializedName(SERIALIZED_NAME_ROWS)
  @javax.annotation.Nullable
  private List<BasketRow> rows = new ArrayList<>();

  public static final String SERIALIZED_NAME_FINGERPRINT = "fingerprint";
  @SerializedName(SERIALIZED_NAME_FINGERPRINT)
  @javax.annotation.Nullable
  private String fingerprint;

  public static final String SERIALIZED_NAME_CREATOR_CODE = "creator_code";
  @SerializedName(SERIALIZED_NAME_CREATOR_CODE)
  @javax.annotation.Nullable
  private String creatorCode;

  public static final String SERIALIZED_NAME_ROUNDUP = "roundup";
  @SerializedName(SERIALIZED_NAME_ROUNDUP)
  @javax.annotation.Nullable
  private Boolean roundup;

  public static final String SERIALIZED_NAME_CANCEL_URL = "cancel_url";
  @SerializedName(SERIALIZED_NAME_CANCEL_URL)
  @javax.annotation.Nullable
  private String cancelUrl;

  public static final String SERIALIZED_NAME_COMPLETE_URL = "complete_url";
  @SerializedName(SERIALIZED_NAME_COMPLETE_URL)
  @javax.annotation.Nullable
  private String completeUrl;

  public static final String SERIALIZED_NAME_COMPLETE_AUTO_REDIRECT = "complete_auto_redirect";
  @SerializedName(SERIALIZED_NAME_COMPLETE_AUTO_REDIRECT)
  @javax.annotation.Nullable
  private Boolean completeAutoRedirect;

  public static final String SERIALIZED_NAME_RECURRING_ITEMS = "recurring_items";
  @SerializedName(SERIALIZED_NAME_RECURRING_ITEMS)
  @javax.annotation.Nullable
  private List<Object> recurringItems = new ArrayList<>();

  public static final String SERIALIZED_NAME_PAYMENT = "payment";
  @SerializedName(SERIALIZED_NAME_PAYMENT)
  @javax.annotation.Nullable
  private Payment payment;

  public static final String SERIALIZED_NAME_CUSTOM = "custom";
  @SerializedName(SERIALIZED_NAME_CUSTOM)
  @javax.annotation.Nullable
  private Object custom;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  @javax.annotation.Nullable
  private BasketLinks links;

  public Basket() {
  }

  public Basket ident(@javax.annotation.Nullable String ident) {
    this.ident = ident;
    return this;
  }

  /**
   * Get ident
   * @return ident
   */
  @javax.annotation.Nullable
  public String getIdent() {
    return ident;
  }

  public void setIdent(@javax.annotation.Nullable String ident) {
    this.ident = ident;
  }


  public Basket expire(@javax.annotation.Nullable String expire) {
    this.expire = expire;
    return this;
  }

  /**
   * Get expire
   * @return expire
   */
  @javax.annotation.Nullable
  public String getExpire() {
    return expire;
  }

  public void setExpire(@javax.annotation.Nullable String expire) {
    this.expire = expire;
  }


  public Basket price(@javax.annotation.Nullable Float price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @javax.annotation.Nullable
  public Float getPrice() {
    return price;
  }

  public void setPrice(@javax.annotation.Nullable Float price) {
    this.price = price;
  }


  public Basket priceDetails(@javax.annotation.Nullable PriceDetails priceDetails) {
    this.priceDetails = priceDetails;
    return this;
  }

  /**
   * Get priceDetails
   * @return priceDetails
   */
  @javax.annotation.Nullable
  public PriceDetails getPriceDetails() {
    return priceDetails;
  }

  public void setPriceDetails(@javax.annotation.Nullable PriceDetails priceDetails) {
    this.priceDetails = priceDetails;
  }


  public Basket isPaymentMethodUpdate(@javax.annotation.Nullable Boolean isPaymentMethodUpdate) {
    this.isPaymentMethodUpdate = isPaymentMethodUpdate;
    return this;
  }

  /**
   * Get isPaymentMethodUpdate
   * @return isPaymentMethodUpdate
   */
  @javax.annotation.Nullable
  public Boolean getIsPaymentMethodUpdate() {
    return isPaymentMethodUpdate;
  }

  public void setIsPaymentMethodUpdate(@javax.annotation.Nullable Boolean isPaymentMethodUpdate) {
    this.isPaymentMethodUpdate = isPaymentMethodUpdate;
  }


  public Basket returnUrl(@javax.annotation.Nullable String returnUrl) {
    this.returnUrl = returnUrl;
    return this;
  }

  /**
   * Get returnUrl
   * @return returnUrl
   */
  @javax.annotation.Nullable
  public String getReturnUrl() {
    return returnUrl;
  }

  public void setReturnUrl(@javax.annotation.Nullable String returnUrl) {
    this.returnUrl = returnUrl;
  }


  public Basket complete(@javax.annotation.Nullable Boolean complete) {
    this.complete = complete;
    return this;
  }

  /**
   * Get complete
   * @return complete
   */
  @javax.annotation.Nullable
  public Boolean getComplete() {
    return complete;
  }

  public void setComplete(@javax.annotation.Nullable Boolean complete) {
    this.complete = complete;
  }


  public Basket tax(@javax.annotation.Nullable BigDecimal tax) {
    this.tax = tax;
    return this;
  }

  /**
   * Get tax
   * @return tax
   */
  @javax.annotation.Nullable
  public BigDecimal getTax() {
    return tax;
  }

  public void setTax(@javax.annotation.Nullable BigDecimal tax) {
    this.tax = tax;
  }


  public Basket username(@javax.annotation.Nullable String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @javax.annotation.Nullable
  public String getUsername() {
    return username;
  }

  public void setUsername(@javax.annotation.Nullable String username) {
    this.username = username;
  }


  public Basket emailImmutable(@javax.annotation.Nullable Boolean emailImmutable) {
    this.emailImmutable = emailImmutable;
    return this;
  }

  /**
   * Get emailImmutable
   * @return emailImmutable
   */
  @javax.annotation.Nullable
  public Boolean getEmailImmutable() {
    return emailImmutable;
  }

  public void setEmailImmutable(@javax.annotation.Nullable Boolean emailImmutable) {
    this.emailImmutable = emailImmutable;
  }


  public Basket discounts(@javax.annotation.Nullable List<Object> discounts) {
    this.discounts = discounts;
    return this;
  }

  public Basket addDiscountsItem(Object discountsItem) {
    if (this.discounts == null) {
      this.discounts = new ArrayList<>();
    }
    this.discounts.add(discountsItem);
    return this;
  }

  /**
   * Get discounts
   * @return discounts
   */
  @javax.annotation.Nullable
  public List<Object> getDiscounts() {
    return discounts;
  }

  public void setDiscounts(@javax.annotation.Nullable List<Object> discounts) {
    this.discounts = discounts;
  }


  public Basket coupons(@javax.annotation.Nullable List<Object> coupons) {
    this.coupons = coupons;
    return this;
  }

  public Basket addCouponsItem(Object couponsItem) {
    if (this.coupons == null) {
      this.coupons = new ArrayList<>();
    }
    this.coupons.add(couponsItem);
    return this;
  }

  /**
   * Get coupons
   * @return coupons
   */
  @javax.annotation.Nullable
  public List<Object> getCoupons() {
    return coupons;
  }

  public void setCoupons(@javax.annotation.Nullable List<Object> coupons) {
    this.coupons = coupons;
  }


  public Basket giftcards(@javax.annotation.Nullable List<Object> giftcards) {
    this.giftcards = giftcards;
    return this;
  }

  public Basket addGiftcardsItem(Object giftcardsItem) {
    if (this.giftcards == null) {
      this.giftcards = new ArrayList<>();
    }
    this.giftcards.add(giftcardsItem);
    return this;
  }

  /**
   * Get giftcards
   * @return giftcards
   */
  @javax.annotation.Nullable
  public List<Object> getGiftcards() {
    return giftcards;
  }

  public void setGiftcards(@javax.annotation.Nullable List<Object> giftcards) {
    this.giftcards = giftcards;
  }


  public Basket address(@javax.annotation.Nullable Address address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  public Address getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable Address address) {
    this.address = address;
  }


  public Basket rows(@javax.annotation.Nullable List<BasketRow> rows) {
    this.rows = rows;
    return this;
  }

  public Basket addRowsItem(BasketRow rowsItem) {
    if (this.rows == null) {
      this.rows = new ArrayList<>();
    }
    this.rows.add(rowsItem);
    return this;
  }

  /**
   * Get rows
   * @return rows
   */
  @javax.annotation.Nullable
  public List<BasketRow> getRows() {
    return rows;
  }

  public void setRows(@javax.annotation.Nullable List<BasketRow> rows) {
    this.rows = rows;
  }


  public Basket fingerprint(@javax.annotation.Nullable String fingerprint) {
    this.fingerprint = fingerprint;
    return this;
  }

  /**
   * Browser fingerprint to identify the user
   * @return fingerprint
   */
  @javax.annotation.Nullable
  public String getFingerprint() {
    return fingerprint;
  }

  public void setFingerprint(@javax.annotation.Nullable String fingerprint) {
    this.fingerprint = fingerprint;
  }


  public Basket creatorCode(@javax.annotation.Nullable String creatorCode) {
    this.creatorCode = creatorCode;
    return this;
  }

  /**
   * The creator code is used to share a percentage of the payment with another party. See more about creator codes at https://docs.tebex.io/creators/tebex-control-panel/engagement/creator-codes
   * @return creatorCode
   */
  @javax.annotation.Nullable
  public String getCreatorCode() {
    return creatorCode;
  }

  public void setCreatorCode(@javax.annotation.Nullable String creatorCode) {
    this.creatorCode = creatorCode;
  }


  public Basket roundup(@javax.annotation.Nullable Boolean roundup) {
    this.roundup = roundup;
    return this;
  }

  /**
   * Get roundup
   * @return roundup
   */
  @javax.annotation.Nullable
  public Boolean getRoundup() {
    return roundup;
  }

  public void setRoundup(@javax.annotation.Nullable Boolean roundup) {
    this.roundup = roundup;
  }


  public Basket cancelUrl(@javax.annotation.Nullable String cancelUrl) {
    this.cancelUrl = cancelUrl;
    return this;
  }

  /**
   * Get cancelUrl
   * @return cancelUrl
   */
  @javax.annotation.Nullable
  public String getCancelUrl() {
    return cancelUrl;
  }

  public void setCancelUrl(@javax.annotation.Nullable String cancelUrl) {
    this.cancelUrl = cancelUrl;
  }


  public Basket completeUrl(@javax.annotation.Nullable String completeUrl) {
    this.completeUrl = completeUrl;
    return this;
  }

  /**
   * Get completeUrl
   * @return completeUrl
   */
  @javax.annotation.Nullable
  public String getCompleteUrl() {
    return completeUrl;
  }

  public void setCompleteUrl(@javax.annotation.Nullable String completeUrl) {
    this.completeUrl = completeUrl;
  }


  public Basket completeAutoRedirect(@javax.annotation.Nullable Boolean completeAutoRedirect) {
    this.completeAutoRedirect = completeAutoRedirect;
    return this;
  }

  /**
   * Get completeAutoRedirect
   * @return completeAutoRedirect
   */
  @javax.annotation.Nullable
  public Boolean getCompleteAutoRedirect() {
    return completeAutoRedirect;
  }

  public void setCompleteAutoRedirect(@javax.annotation.Nullable Boolean completeAutoRedirect) {
    this.completeAutoRedirect = completeAutoRedirect;
  }


  public Basket recurringItems(@javax.annotation.Nullable List<Object> recurringItems) {
    this.recurringItems = recurringItems;
    return this;
  }

  public Basket addRecurringItemsItem(Object recurringItemsItem) {
    if (this.recurringItems == null) {
      this.recurringItems = new ArrayList<>();
    }
    this.recurringItems.add(recurringItemsItem);
    return this;
  }

  /**
   * Get recurringItems
   * @return recurringItems
   */
  @javax.annotation.Nullable
  public List<Object> getRecurringItems() {
    return recurringItems;
  }

  public void setRecurringItems(@javax.annotation.Nullable List<Object> recurringItems) {
    this.recurringItems = recurringItems;
  }


  public Basket payment(@javax.annotation.Nullable Payment payment) {
    this.payment = payment;
    return this;
  }

  /**
   * Get payment
   * @return payment
   */
  @javax.annotation.Nullable
  public Payment getPayment() {
    return payment;
  }

  public void setPayment(@javax.annotation.Nullable Payment payment) {
    this.payment = payment;
  }


  public Basket custom(@javax.annotation.Nullable Object custom) {
    this.custom = custom;
    return this;
  }

  /**
   * Get custom
   * @return custom
   */
  @javax.annotation.Nullable
  public Object getCustom() {
    return custom;
  }

  public void setCustom(@javax.annotation.Nullable Object custom) {
    this.custom = custom;
  }


  public Basket links(@javax.annotation.Nullable BasketLinks links) {
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  public BasketLinks getLinks() {
    return links;
  }

  public void setLinks(@javax.annotation.Nullable BasketLinks links) {
    this.links = links;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Basket instance itself
   */
  public Basket putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Basket basket = (Basket) o;
    return Objects.equals(this.ident, basket.ident) &&
        Objects.equals(this.expire, basket.expire) &&
        Objects.equals(this.price, basket.price) &&
        Objects.equals(this.priceDetails, basket.priceDetails) &&
        Objects.equals(this.isPaymentMethodUpdate, basket.isPaymentMethodUpdate) &&
        Objects.equals(this.returnUrl, basket.returnUrl) &&
        Objects.equals(this.complete, basket.complete) &&
        Objects.equals(this.tax, basket.tax) &&
        Objects.equals(this.username, basket.username) &&
        Objects.equals(this.emailImmutable, basket.emailImmutable) &&
        Objects.equals(this.discounts, basket.discounts) &&
        Objects.equals(this.coupons, basket.coupons) &&
        Objects.equals(this.giftcards, basket.giftcards) &&
        Objects.equals(this.address, basket.address) &&
        Objects.equals(this.rows, basket.rows) &&
        Objects.equals(this.fingerprint, basket.fingerprint) &&
        Objects.equals(this.creatorCode, basket.creatorCode) &&
        Objects.equals(this.roundup, basket.roundup) &&
        Objects.equals(this.cancelUrl, basket.cancelUrl) &&
        Objects.equals(this.completeUrl, basket.completeUrl) &&
        Objects.equals(this.completeAutoRedirect, basket.completeAutoRedirect) &&
        Objects.equals(this.recurringItems, basket.recurringItems) &&
        Objects.equals(this.payment, basket.payment) &&
        Objects.equals(this.custom, basket.custom) &&
        Objects.equals(this.links, basket.links)&&
        Objects.equals(this.additionalProperties, basket.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ident, expire, price, priceDetails, isPaymentMethodUpdate, returnUrl, complete, tax, username, emailImmutable, discounts, coupons, giftcards, address, rows, fingerprint, creatorCode, roundup, cancelUrl, completeUrl, completeAutoRedirect, recurringItems, payment, custom, links, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Basket {\n");
    sb.append("    ident: ").append(toIndentedString(ident)).append("\n");
    sb.append("    expire: ").append(toIndentedString(expire)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceDetails: ").append(toIndentedString(priceDetails)).append("\n");
    sb.append("    isPaymentMethodUpdate: ").append(toIndentedString(isPaymentMethodUpdate)).append("\n");
    sb.append("    returnUrl: ").append(toIndentedString(returnUrl)).append("\n");
    sb.append("    complete: ").append(toIndentedString(complete)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    emailImmutable: ").append(toIndentedString(emailImmutable)).append("\n");
    sb.append("    discounts: ").append(toIndentedString(discounts)).append("\n");
    sb.append("    coupons: ").append(toIndentedString(coupons)).append("\n");
    sb.append("    giftcards: ").append(toIndentedString(giftcards)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    fingerprint: ").append(toIndentedString(fingerprint)).append("\n");
    sb.append("    creatorCode: ").append(toIndentedString(creatorCode)).append("\n");
    sb.append("    roundup: ").append(toIndentedString(roundup)).append("\n");
    sb.append("    cancelUrl: ").append(toIndentedString(cancelUrl)).append("\n");
    sb.append("    completeUrl: ").append(toIndentedString(completeUrl)).append("\n");
    sb.append("    completeAutoRedirect: ").append(toIndentedString(completeAutoRedirect)).append("\n");
    sb.append("    recurringItems: ").append(toIndentedString(recurringItems)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("ident", "expire", "price", "priceDetails", "isPaymentMethodUpdate", "returnUrl", "complete", "tax", "username", "email_immutable", "discounts", "coupons", "giftcards", "address", "rows", "fingerprint", "creator_code", "roundup", "cancel_url", "complete_url", "complete_auto_redirect", "recurring_items", "payment", "custom", "links"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Basket
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Basket.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Basket is not found in the empty JSON string", Basket.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("ident") != null && !jsonObj.get("ident").isJsonNull()) && !jsonObj.get("ident").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ident` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ident").toString()));
      }
      if ((jsonObj.get("expire") != null && !jsonObj.get("expire").isJsonNull()) && !jsonObj.get("expire").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `expire` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expire").toString()));
      }
      // validate the optional field `priceDetails`
      if (jsonObj.get("priceDetails") != null && !jsonObj.get("priceDetails").isJsonNull()) {
        PriceDetails.validateJsonElement(jsonObj.get("priceDetails"));
      }
      if ((jsonObj.get("returnUrl") != null && !jsonObj.get("returnUrl").isJsonNull()) && !jsonObj.get("returnUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `returnUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("returnUrl").toString()));
      }
      if ((jsonObj.get("username") != null && !jsonObj.get("username").isJsonNull()) && !jsonObj.get("username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("username").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("discounts") != null && !jsonObj.get("discounts").isJsonNull() && !jsonObj.get("discounts").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `discounts` to be an array in the JSON string but got `%s`", jsonObj.get("discounts").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("coupons") != null && !jsonObj.get("coupons").isJsonNull() && !jsonObj.get("coupons").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `coupons` to be an array in the JSON string but got `%s`", jsonObj.get("coupons").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("giftcards") != null && !jsonObj.get("giftcards").isJsonNull() && !jsonObj.get("giftcards").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `giftcards` to be an array in the JSON string but got `%s`", jsonObj.get("giftcards").toString()));
      }
      // validate the optional field `address`
      if (jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) {
        Address.validateJsonElement(jsonObj.get("address"));
      }
      if (jsonObj.get("rows") != null && !jsonObj.get("rows").isJsonNull()) {
        JsonArray jsonArrayrows = jsonObj.getAsJsonArray("rows");
        if (jsonArrayrows != null) {
          // ensure the json data is an array
          if (!jsonObj.get("rows").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rows` to be an array in the JSON string but got `%s`", jsonObj.get("rows").toString()));
          }

          // validate the optional field `rows` (array)
          for (int i = 0; i < jsonArrayrows.size(); i++) {
            BasketRow.validateJsonElement(jsonArrayrows.get(i));
          };
        }
      }
      if ((jsonObj.get("fingerprint") != null && !jsonObj.get("fingerprint").isJsonNull()) && !jsonObj.get("fingerprint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fingerprint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fingerprint").toString()));
      }
      if ((jsonObj.get("creator_code") != null && !jsonObj.get("creator_code").isJsonNull()) && !jsonObj.get("creator_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `creator_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creator_code").toString()));
      }
      if ((jsonObj.get("cancel_url") != null && !jsonObj.get("cancel_url").isJsonNull()) && !jsonObj.get("cancel_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cancel_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancel_url").toString()));
      }
      if ((jsonObj.get("complete_url") != null && !jsonObj.get("complete_url").isJsonNull()) && !jsonObj.get("complete_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `complete_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("complete_url").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("recurring_items") != null && !jsonObj.get("recurring_items").isJsonNull() && !jsonObj.get("recurring_items").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recurring_items` to be an array in the JSON string but got `%s`", jsonObj.get("recurring_items").toString()));
      }
      // validate the optional field `payment`
      if (jsonObj.get("payment") != null && !jsonObj.get("payment").isJsonNull()) {
        Payment.validateJsonElement(jsonObj.get("payment"));
      }
      // validate the optional field `links`
      if (jsonObj.get("links") != null && !jsonObj.get("links").isJsonNull()) {
        BasketLinks.validateJsonElement(jsonObj.get("links"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Basket.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Basket' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Basket> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Basket.class));

       return (TypeAdapter<T>) new TypeAdapter<Basket>() {
           @Override
           public void write(JsonWriter out, Basket value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Basket read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             Basket instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Basket given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Basket
   * @throws IOException if the JSON string is invalid with respect to Basket
   */
  public static Basket fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Basket.class);
  }

  /**
   * Convert an instance of Basket to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

