/*
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.5
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.checkout.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tebex.checkout.model.PaymentCustomer;
import io.tebex.checkout.model.PaymentFees;
import io.tebex.checkout.model.PaymentPaymentMethod;
import io.tebex.checkout.model.PaymentPrice;
import io.tebex.checkout.model.PaymentProductsInner;
import io.tebex.checkout.model.PaymentStatus;
import io.tebex.checkout.model.RevenueShare;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.tebex.checkout.invoker.JSON;

/**
 * Payment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Payment {
  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transaction_id";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  @javax.annotation.Nullable
  private String transactionId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private PaymentStatus status;

  public static final String SERIALIZED_NAME_PAYMENT_SEQUENCE = "payment_sequence";
  @SerializedName(SERIALIZED_NAME_PAYMENT_SEQUENCE)
  @javax.annotation.Nullable
  private String paymentSequence;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @javax.annotation.Nullable
  private PaymentPrice price;

  public static final String SERIALIZED_NAME_PRICE_PAID = "price_paid";
  @SerializedName(SERIALIZED_NAME_PRICE_PAID)
  @javax.annotation.Nullable
  private PaymentPrice pricePaid;

  public static final String SERIALIZED_NAME_PAYMENT_METHOD = "payment_method";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHOD)
  @javax.annotation.Nullable
  private PaymentPaymentMethod paymentMethod;

  public static final String SERIALIZED_NAME_REVENUE_SHARE = "revenue_share";
  @SerializedName(SERIALIZED_NAME_REVENUE_SHARE)
  @javax.annotation.Nullable
  private List<RevenueShare> revenueShare = new ArrayList<>();

  public static final String SERIALIZED_NAME_DECLINE_REASON = "decline_reason";
  @SerializedName(SERIALIZED_NAME_DECLINE_REASON)
  @javax.annotation.Nullable
  private String declineReason;

  public static final String SERIALIZED_NAME_FEES = "fees";
  @SerializedName(SERIALIZED_NAME_FEES)
  @javax.annotation.Nullable
  private PaymentFees fees;

  public static final String SERIALIZED_NAME_CUSTOMER = "customer";
  @SerializedName(SERIALIZED_NAME_CUSTOMER)
  @javax.annotation.Nullable
  private PaymentCustomer customer;

  public static final String SERIALIZED_NAME_PRODUCTS = "products";
  @SerializedName(SERIALIZED_NAME_PRODUCTS)
  @javax.annotation.Nullable
  private List<PaymentProductsInner> products = new ArrayList<>();

  public static final String SERIALIZED_NAME_COUPONS = "coupons";
  @SerializedName(SERIALIZED_NAME_COUPONS)
  @javax.annotation.Nullable
  private List<Object> coupons = new ArrayList<>();

  public static final String SERIALIZED_NAME_GIFT_CARDS = "gift_cards";
  @SerializedName(SERIALIZED_NAME_GIFT_CARDS)
  @javax.annotation.Nullable
  private List<Object> giftCards = new ArrayList<>();

  public static final String SERIALIZED_NAME_RECURRING_PAYMENT_REFERENCE = "recurring_payment_reference";
  @SerializedName(SERIALIZED_NAME_RECURRING_PAYMENT_REFERENCE)
  @javax.annotation.Nullable
  private String recurringPaymentReference;

  public static final String SERIALIZED_NAME_CUSTOM = "custom";
  @SerializedName(SERIALIZED_NAME_CUSTOM)
  @javax.annotation.Nullable
  private Object custom;

  public Payment() {
  }

  public Payment transactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Get transactionId
   * @return transactionId
   */
  @javax.annotation.Nullable
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(@javax.annotation.Nullable String transactionId) {
    this.transactionId = transactionId;
  }


  public Payment status(@javax.annotation.Nullable PaymentStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public PaymentStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable PaymentStatus status) {
    this.status = status;
  }


  public Payment paymentSequence(@javax.annotation.Nullable String paymentSequence) {
    this.paymentSequence = paymentSequence;
    return this;
  }

  /**
   * Get paymentSequence
   * @return paymentSequence
   */
  @javax.annotation.Nullable
  public String getPaymentSequence() {
    return paymentSequence;
  }

  public void setPaymentSequence(@javax.annotation.Nullable String paymentSequence) {
    this.paymentSequence = paymentSequence;
  }


  public Payment createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Payment price(@javax.annotation.Nullable PaymentPrice price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @javax.annotation.Nullable
  public PaymentPrice getPrice() {
    return price;
  }

  public void setPrice(@javax.annotation.Nullable PaymentPrice price) {
    this.price = price;
  }


  public Payment pricePaid(@javax.annotation.Nullable PaymentPrice pricePaid) {
    this.pricePaid = pricePaid;
    return this;
  }

  /**
   * Get pricePaid
   * @return pricePaid
   */
  @javax.annotation.Nullable
  public PaymentPrice getPricePaid() {
    return pricePaid;
  }

  public void setPricePaid(@javax.annotation.Nullable PaymentPrice pricePaid) {
    this.pricePaid = pricePaid;
  }


  public Payment paymentMethod(@javax.annotation.Nullable PaymentPaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

  /**
   * Get paymentMethod
   * @return paymentMethod
   */
  @javax.annotation.Nullable
  public PaymentPaymentMethod getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(@javax.annotation.Nullable PaymentPaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public Payment revenueShare(@javax.annotation.Nullable List<RevenueShare> revenueShare) {
    this.revenueShare = revenueShare;
    return this;
  }

  public Payment addRevenueShareItem(RevenueShare revenueShareItem) {
    if (this.revenueShare == null) {
      this.revenueShare = new ArrayList<>();
    }
    this.revenueShare.add(revenueShareItem);
    return this;
  }

  /**
   * Get revenueShare
   * @return revenueShare
   */
  @javax.annotation.Nullable
  public List<RevenueShare> getRevenueShare() {
    return revenueShare;
  }

  public void setRevenueShare(@javax.annotation.Nullable List<RevenueShare> revenueShare) {
    this.revenueShare = revenueShare;
  }


  public Payment declineReason(@javax.annotation.Nullable String declineReason) {
    this.declineReason = declineReason;
    return this;
  }

  /**
   * Get declineReason
   * @return declineReason
   */
  @javax.annotation.Nullable
  public String getDeclineReason() {
    return declineReason;
  }

  public void setDeclineReason(@javax.annotation.Nullable String declineReason) {
    this.declineReason = declineReason;
  }


  public Payment fees(@javax.annotation.Nullable PaymentFees fees) {
    this.fees = fees;
    return this;
  }

  /**
   * Get fees
   * @return fees
   */
  @javax.annotation.Nullable
  public PaymentFees getFees() {
    return fees;
  }

  public void setFees(@javax.annotation.Nullable PaymentFees fees) {
    this.fees = fees;
  }


  public Payment customer(@javax.annotation.Nullable PaymentCustomer customer) {
    this.customer = customer;
    return this;
  }

  /**
   * Get customer
   * @return customer
   */
  @javax.annotation.Nullable
  public PaymentCustomer getCustomer() {
    return customer;
  }

  public void setCustomer(@javax.annotation.Nullable PaymentCustomer customer) {
    this.customer = customer;
  }


  public Payment products(@javax.annotation.Nullable List<PaymentProductsInner> products) {
    this.products = products;
    return this;
  }

  public Payment addProductsItem(PaymentProductsInner productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

  /**
   * Get products
   * @return products
   */
  @javax.annotation.Nullable
  public List<PaymentProductsInner> getProducts() {
    return products;
  }

  public void setProducts(@javax.annotation.Nullable List<PaymentProductsInner> products) {
    this.products = products;
  }


  public Payment coupons(@javax.annotation.Nullable List<Object> coupons) {
    this.coupons = coupons;
    return this;
  }

  public Payment addCouponsItem(Object couponsItem) {
    if (this.coupons == null) {
      this.coupons = new ArrayList<>();
    }
    this.coupons.add(couponsItem);
    return this;
  }

  /**
   * Get coupons
   * @return coupons
   */
  @javax.annotation.Nullable
  public List<Object> getCoupons() {
    return coupons;
  }

  public void setCoupons(@javax.annotation.Nullable List<Object> coupons) {
    this.coupons = coupons;
  }


  public Payment giftCards(@javax.annotation.Nullable List<Object> giftCards) {
    this.giftCards = giftCards;
    return this;
  }

  public Payment addGiftCardsItem(Object giftCardsItem) {
    if (this.giftCards == null) {
      this.giftCards = new ArrayList<>();
    }
    this.giftCards.add(giftCardsItem);
    return this;
  }

  /**
   * Get giftCards
   * @return giftCards
   */
  @javax.annotation.Nullable
  public List<Object> getGiftCards() {
    return giftCards;
  }

  public void setGiftCards(@javax.annotation.Nullable List<Object> giftCards) {
    this.giftCards = giftCards;
  }


  public Payment recurringPaymentReference(@javax.annotation.Nullable String recurringPaymentReference) {
    this.recurringPaymentReference = recurringPaymentReference;
    return this;
  }

  /**
   * Get recurringPaymentReference
   * @return recurringPaymentReference
   */
  @javax.annotation.Nullable
  public String getRecurringPaymentReference() {
    return recurringPaymentReference;
  }

  public void setRecurringPaymentReference(@javax.annotation.Nullable String recurringPaymentReference) {
    this.recurringPaymentReference = recurringPaymentReference;
  }


  public Payment custom(@javax.annotation.Nullable Object custom) {
    this.custom = custom;
    return this;
  }

  /**
   * Get custom
   * @return custom
   */
  @javax.annotation.Nullable
  public Object getCustom() {
    return custom;
  }

  public void setCustom(@javax.annotation.Nullable Object custom) {
    this.custom = custom;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payment payment = (Payment) o;
    return Objects.equals(this.transactionId, payment.transactionId) &&
        Objects.equals(this.status, payment.status) &&
        Objects.equals(this.paymentSequence, payment.paymentSequence) &&
        Objects.equals(this.createdAt, payment.createdAt) &&
        Objects.equals(this.price, payment.price) &&
        Objects.equals(this.pricePaid, payment.pricePaid) &&
        Objects.equals(this.paymentMethod, payment.paymentMethod) &&
        Objects.equals(this.revenueShare, payment.revenueShare) &&
        Objects.equals(this.declineReason, payment.declineReason) &&
        Objects.equals(this.fees, payment.fees) &&
        Objects.equals(this.customer, payment.customer) &&
        Objects.equals(this.products, payment.products) &&
        Objects.equals(this.coupons, payment.coupons) &&
        Objects.equals(this.giftCards, payment.giftCards) &&
        Objects.equals(this.recurringPaymentReference, payment.recurringPaymentReference) &&
        Objects.equals(this.custom, payment.custom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, status, paymentSequence, createdAt, price, pricePaid, paymentMethod, revenueShare, declineReason, fees, customer, products, coupons, giftCards, recurringPaymentReference, custom);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payment {\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    paymentSequence: ").append(toIndentedString(paymentSequence)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    pricePaid: ").append(toIndentedString(pricePaid)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    revenueShare: ").append(toIndentedString(revenueShare)).append("\n");
    sb.append("    declineReason: ").append(toIndentedString(declineReason)).append("\n");
    sb.append("    fees: ").append(toIndentedString(fees)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    coupons: ").append(toIndentedString(coupons)).append("\n");
    sb.append("    giftCards: ").append(toIndentedString(giftCards)).append("\n");
    sb.append("    recurringPaymentReference: ").append(toIndentedString(recurringPaymentReference)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("transaction_id", "status", "payment_sequence", "created_at", "price", "price_paid", "payment_method", "revenue_share", "decline_reason", "fees", "customer", "products", "coupons", "gift_cards", "recurring_payment_reference", "custom"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Payment
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Payment.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Payment is not found in the empty JSON string", Payment.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Payment.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Payment` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("transaction_id") != null && !jsonObj.get("transaction_id").isJsonNull()) && !jsonObj.get("transaction_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transaction_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transaction_id").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        PaymentStatus.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("payment_sequence") != null && !jsonObj.get("payment_sequence").isJsonNull()) && !jsonObj.get("payment_sequence").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payment_sequence` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payment_sequence").toString()));
      }
      // validate the optional field `price`
      if (jsonObj.get("price") != null && !jsonObj.get("price").isJsonNull()) {
        PaymentPrice.validateJsonElement(jsonObj.get("price"));
      }
      // validate the optional field `price_paid`
      if (jsonObj.get("price_paid") != null && !jsonObj.get("price_paid").isJsonNull()) {
        PaymentPrice.validateJsonElement(jsonObj.get("price_paid"));
      }
      // validate the optional field `payment_method`
      if (jsonObj.get("payment_method") != null && !jsonObj.get("payment_method").isJsonNull()) {
        PaymentPaymentMethod.validateJsonElement(jsonObj.get("payment_method"));
      }
      if (jsonObj.get("revenue_share") != null && !jsonObj.get("revenue_share").isJsonNull()) {
        JsonArray jsonArrayrevenueShare = jsonObj.getAsJsonArray("revenue_share");
        if (jsonArrayrevenueShare != null) {
          // ensure the json data is an array
          if (!jsonObj.get("revenue_share").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `revenue_share` to be an array in the JSON string but got `%s`", jsonObj.get("revenue_share").toString()));
          }

          // validate the optional field `revenue_share` (array)
          for (int i = 0; i < jsonArrayrevenueShare.size(); i++) {
            RevenueShare.validateJsonElement(jsonArrayrevenueShare.get(i));
          };
        }
      }
      if ((jsonObj.get("decline_reason") != null && !jsonObj.get("decline_reason").isJsonNull()) && !jsonObj.get("decline_reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `decline_reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("decline_reason").toString()));
      }
      // validate the optional field `fees`
      if (jsonObj.get("fees") != null && !jsonObj.get("fees").isJsonNull()) {
        PaymentFees.validateJsonElement(jsonObj.get("fees"));
      }
      // validate the optional field `customer`
      if (jsonObj.get("customer") != null && !jsonObj.get("customer").isJsonNull()) {
        PaymentCustomer.validateJsonElement(jsonObj.get("customer"));
      }
      if (jsonObj.get("products") != null && !jsonObj.get("products").isJsonNull()) {
        JsonArray jsonArrayproducts = jsonObj.getAsJsonArray("products");
        if (jsonArrayproducts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("products").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `products` to be an array in the JSON string but got `%s`", jsonObj.get("products").toString()));
          }

          // validate the optional field `products` (array)
          for (int i = 0; i < jsonArrayproducts.size(); i++) {
            PaymentProductsInner.validateJsonElement(jsonArrayproducts.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("coupons") != null && !jsonObj.get("coupons").isJsonNull() && !jsonObj.get("coupons").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `coupons` to be an array in the JSON string but got `%s`", jsonObj.get("coupons").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("gift_cards") != null && !jsonObj.get("gift_cards").isJsonNull() && !jsonObj.get("gift_cards").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `gift_cards` to be an array in the JSON string but got `%s`", jsonObj.get("gift_cards").toString()));
      }
      if ((jsonObj.get("recurring_payment_reference") != null && !jsonObj.get("recurring_payment_reference").isJsonNull()) && !jsonObj.get("recurring_payment_reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recurring_payment_reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recurring_payment_reference").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Payment.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Payment' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Payment> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Payment.class));

       return (TypeAdapter<T>) new TypeAdapter<Payment>() {
           @Override
           public void write(JsonWriter out, Payment value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Payment read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Payment given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Payment
   * @throws IOException if the JSON string is invalid with respect to Payment
   */
  public static Payment fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Payment.class);
  }

  /**
   * Convert an instance of Payment to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

