/*
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.headless.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tebex.headless.model.ModelPackage;
import io.tebex.headless.model.TierPendingDowngradePackage;
import io.tebex.headless.model.TierStatus;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.tebex.headless.invoker.JSON;

/**
 * Tier
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Tier {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_USERNAME_ID = "username_id";
  @SerializedName(SERIALIZED_NAME_USERNAME_ID)
  @javax.annotation.Nullable
  private String usernameId;

  public static final String SERIALIZED_NAME_PACKAGE = "package";
  @SerializedName(SERIALIZED_NAME_PACKAGE)
  @javax.annotation.Nullable
  private ModelPackage _package;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  @javax.annotation.Nullable
  private Boolean active;

  public static final String SERIALIZED_NAME_RECURRING_PAYMENT_REFERENCE = "recurring_payment_reference";
  @SerializedName(SERIALIZED_NAME_RECURRING_PAYMENT_REFERENCE)
  @javax.annotation.Nullable
  private String recurringPaymentReference;

  public static final String SERIALIZED_NAME_NEXT_PAYMENT_DATE = "next_payment_date";
  @SerializedName(SERIALIZED_NAME_NEXT_PAYMENT_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime nextPaymentDate;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private TierStatus status;

  public static final String SERIALIZED_NAME_PENDING_DOWNGRADE_PACKAGE = "pending_downgrade_package";
  @SerializedName(SERIALIZED_NAME_PENDING_DOWNGRADE_PACKAGE)
  @javax.annotation.Nullable
  private TierPendingDowngradePackage pendingDowngradePackage;

  public Tier() {
  }

  public Tier id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Tier createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The date and time when the tier became active
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Tier usernameId(@javax.annotation.Nullable String usernameId) {
    this.usernameId = usernameId;
    return this;
  }

  /**
   * The user&#39;s username ID. For Steam, this is a numeric representation of their Steam64ID
   * @return usernameId
   */
  @javax.annotation.Nullable
  public String getUsernameId() {
    return usernameId;
  }

  public void setUsernameId(@javax.annotation.Nullable String usernameId) {
    this.usernameId = usernameId;
  }


  public Tier _package(@javax.annotation.Nullable ModelPackage _package) {
    this._package = _package;
    return this;
  }

  /**
   * Get _package
   * @return _package
   */
  @javax.annotation.Nullable
  public ModelPackage getPackage() {
    return _package;
  }

  public void setPackage(@javax.annotation.Nullable ModelPackage _package) {
    this._package = _package;
  }


  public Tier active(@javax.annotation.Nullable Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * True if the tier is currently active.
   * @return active
   */
  @javax.annotation.Nullable
  public Boolean getActive() {
    return active;
  }

  public void setActive(@javax.annotation.Nullable Boolean active) {
    this.active = active;
  }


  public Tier recurringPaymentReference(@javax.annotation.Nullable String recurringPaymentReference) {
    this.recurringPaymentReference = recurringPaymentReference;
    return this;
  }

  /**
   * The ID of the recurring payment this tier is attached to.
   * @return recurringPaymentReference
   */
  @javax.annotation.Nullable
  public String getRecurringPaymentReference() {
    return recurringPaymentReference;
  }

  public void setRecurringPaymentReference(@javax.annotation.Nullable String recurringPaymentReference) {
    this.recurringPaymentReference = recurringPaymentReference;
  }


  public Tier nextPaymentDate(@javax.annotation.Nullable OffsetDateTime nextPaymentDate) {
    this.nextPaymentDate = nextPaymentDate;
    return this;
  }

  /**
   * The date and time of the next payment for this tier.
   * @return nextPaymentDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getNextPaymentDate() {
    return nextPaymentDate;
  }

  public void setNextPaymentDate(@javax.annotation.Nullable OffsetDateTime nextPaymentDate) {
    this.nextPaymentDate = nextPaymentDate;
  }


  public Tier status(@javax.annotation.Nullable TierStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public TierStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable TierStatus status) {
    this.status = status;
  }


  public Tier pendingDowngradePackage(@javax.annotation.Nullable TierPendingDowngradePackage pendingDowngradePackage) {
    this.pendingDowngradePackage = pendingDowngradePackage;
    return this;
  }

  /**
   * Get pendingDowngradePackage
   * @return pendingDowngradePackage
   */
  @javax.annotation.Nullable
  public TierPendingDowngradePackage getPendingDowngradePackage() {
    return pendingDowngradePackage;
  }

  public void setPendingDowngradePackage(@javax.annotation.Nullable TierPendingDowngradePackage pendingDowngradePackage) {
    this.pendingDowngradePackage = pendingDowngradePackage;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Tier instance itself
   */
  public Tier putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tier tier = (Tier) o;
    return Objects.equals(this.id, tier.id) &&
        Objects.equals(this.createdAt, tier.createdAt) &&
        Objects.equals(this.usernameId, tier.usernameId) &&
        Objects.equals(this._package, tier._package) &&
        Objects.equals(this.active, tier.active) &&
        Objects.equals(this.recurringPaymentReference, tier.recurringPaymentReference) &&
        Objects.equals(this.nextPaymentDate, tier.nextPaymentDate) &&
        Objects.equals(this.status, tier.status) &&
        Objects.equals(this.pendingDowngradePackage, tier.pendingDowngradePackage)&&
        Objects.equals(this.additionalProperties, tier.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, usernameId, _package, active, recurringPaymentReference, nextPaymentDate, status, pendingDowngradePackage, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tier {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    usernameId: ").append(toIndentedString(usernameId)).append("\n");
    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    recurringPaymentReference: ").append(toIndentedString(recurringPaymentReference)).append("\n");
    sb.append("    nextPaymentDate: ").append(toIndentedString(nextPaymentDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    pendingDowngradePackage: ").append(toIndentedString(pendingDowngradePackage)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "created_at", "username_id", "package", "active", "recurring_payment_reference", "next_payment_date", "status", "pending_downgrade_package"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Tier
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Tier.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Tier is not found in the empty JSON string", Tier.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("username_id") != null && !jsonObj.get("username_id").isJsonNull()) && !jsonObj.get("username_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `username_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("username_id").toString()));
      }
      // validate the optional field `package`
      if (jsonObj.get("package") != null && !jsonObj.get("package").isJsonNull()) {
        ModelPackage.validateJsonElement(jsonObj.get("package"));
      }
      if ((jsonObj.get("recurring_payment_reference") != null && !jsonObj.get("recurring_payment_reference").isJsonNull()) && !jsonObj.get("recurring_payment_reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recurring_payment_reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recurring_payment_reference").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        TierStatus.validateJsonElement(jsonObj.get("status"));
      }
      // validate the optional field `pending_downgrade_package`
      if (jsonObj.get("pending_downgrade_package") != null && !jsonObj.get("pending_downgrade_package").isJsonNull()) {
        TierPendingDowngradePackage.validateJsonElement(jsonObj.get("pending_downgrade_package"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Tier.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Tier' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Tier> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Tier.class));

       return (TypeAdapter<T>) new TypeAdapter<Tier>() {
           @Override
           public void write(JsonWriter out, Tier value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Tier read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             Tier instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Tier given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Tier
   * @throws IOException if the JSON string is invalid with respect to Tier
   */
  public static Tier fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Tier.class);
  }

  /**
   * Convert an instance of Tier to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

