/*
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.headless.api;

import io.tebex.headless.invoker.ApiException;
import io.tebex.headless.model.AddBasketPackageRequest;
import io.tebex.headless.model.BasketResponse;
import io.tebex.headless.model.RemoveBasketPackageRequest;
import io.tebex.headless.model.UpdatePackageQuantityRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BasketsApi
 */
@Disabled
public class BasketsApiTest {

    private final BasketsApi api = new BasketsApi();

    /**
     * Add package to basket
     *
     * Add a package with the given ID to the basket.  To add a package belonging to a dynamic category, set &#x60;dynamic&#x60; to &#x60;true&#x60;. Without this property the API will treat the request as a normal package ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addBasketPackageTest() throws ApiException {
        String basketIdent = null;
        AddBasketPackageRequest addBasketPackageRequest = null;
        BasketResponse response = api.addBasketPackage(basketIdent, addBasketPackageRequest);
        // TODO: test validations
    }

    /**
     * Remove a package from a basket
     *
     * Remove the given package ID from the basket.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeBasketPackageTest() throws ApiException {
        String basketIdent = null;
        RemoveBasketPackageRequest removeBasketPackageRequest = null;
        BasketResponse response = api.removeBasketPackage(basketIdent, removeBasketPackageRequest);
        // TODO: test validations
    }

    /**
     * Update package quantity
     *
     * Sets the quantity of the given item in the basket. The user must be logged in before the quantity can be changed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePackageQuantityTest() throws ApiException {
        String basketIdent = null;
        String packageId = null;
        UpdatePackageQuantityRequest updatePackageQuantityRequest = null;
        api.updatePackageQuantity(basketIdent, packageId, updatePackageQuantityRequest);
        // TODO: test validations
    }

}
