/*
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.headless.api;

import io.tebex.headless.invoker.ApiException;
import io.tebex.headless.model.ApplyCoupon200Response;
import io.tebex.headless.model.ApplyCouponRequest;
import io.tebex.headless.model.ApplyCreatorCode200Response;
import io.tebex.headless.model.ApplyCreatorCodeRequest;
import io.tebex.headless.model.ApplyGiftCard200Response;
import io.tebex.headless.model.BasketAuthResponseInner;
import io.tebex.headless.model.BasketResponse;
import io.tebex.headless.model.CMSPagesResponse;
import io.tebex.headless.model.CategoryResponse;
import io.tebex.headless.model.CreateBasketRequest;
import io.tebex.headless.model.DynamicPackagesRequest;
import io.tebex.headless.model.DynamicPackagesResponse;
import io.tebex.headless.model.GiftCard;
import io.tebex.headless.model.ModulesResponse;
import io.tebex.headless.model.PackageResponse;
import io.tebex.headless.model.RemoveGiftCardRequest;
import io.tebex.headless.model.SingleCategoryResponse;
import io.tebex.headless.model.SinglePackageResponse;
import io.tebex.headless.model.UpdateTierRequest;
import io.tebex.headless.model.UpdateTierResponse;
import io.tebex.headless.model.WebstoreResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HeadlessApi
 */
@Disabled
public class HeadlessApiTest {

    private final HeadlessApi api = new HeadlessApi();

    /**
     * Apply a coupon
     *
     * Applies a coupon to a basket.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applyCouponTest() throws ApiException {
        String basketIdent = null;
        ApplyCouponRequest applyCouponRequest = null;
        ApplyCoupon200Response response = api.applyCoupon(basketIdent, applyCouponRequest);
        // TODO: test validations
    }

    /**
     * Apply a creator code
     *
     * Applies a creator code to a basket.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applyCreatorCodeTest() throws ApiException {
        String basketIdent = null;
        ApplyCreatorCodeRequest applyCreatorCodeRequest = null;
        ApplyCreatorCode200Response response = api.applyCreatorCode(basketIdent, applyCreatorCodeRequest);
        // TODO: test validations
    }

    /**
     * Apply a gift card
     *
     * Applies a gift card to the basket.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applyGiftCardTest() throws ApiException {
        String basketIdent = null;
        GiftCard giftCard = null;
        ApplyGiftCard200Response response = api.applyGiftCard(basketIdent, giftCard);
        // TODO: test validations
    }

    /**
     * Create a new basket
     *
     * Creates a new basket for use during checkout.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createBasketTest() throws ApiException {
        CreateBasketRequest createBasketRequest = null;
        BasketResponse response = api.createBasket(createBasketRequest);
        // TODO: test validations
    }

    /**
     * Add packages to a dynamic category for a basket.
     *
     * Populates a dynamic category with custom packages for the given basket. Dynamic categories are created in the creator panel with the type &#x60;dynamic&#x60;, and are typically populated in response to a &#x60;basket.authenticated&#x60; webhook.  Once created, the packages can be fetched using the category endpoints with both &#x60;includePackages&#x3D;1&#x60; and &#x60;basketIdent&#x60; provided.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createDynamicPackageTest() throws ApiException {
        String basketIdent = null;
        DynamicPackagesRequest dynamicPackagesRequest = null;
        DynamicPackagesResponse response = api.createDynamicPackage(basketIdent, dynamicPackagesRequest);
        // TODO: test validations
    }

    /**
     * Get all packages
     *
     * Gets all packages from a webstore.  Note: this endpoint does not support packages belonging to dynamic categories. Use the category endpoints with &#x60;includePackages&#x3D;1&#x60; and &#x60;basketIdent&#x60; to fetch dynamic packages.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllPackagesTest() throws ApiException {
        PackageResponse response = api.getAllPackages();
        // TODO: test validations
    }

    /**
     * Get packages
     *
     * Gets all packages from a webstore.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllPackagesWithAuthedIPTest() throws ApiException {
        String ipAddress = null;
        PackageResponse response = api.getAllPackagesWithAuthedIP(ipAddress);
        // TODO: test validations
    }

    /**
     * Get packages available for IP and basket
     *
     * Gets all packages from a webstore.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllPackagesWithAuthedIPAndBasketTest() throws ApiException {
        String basketIdent = null;
        String ipAddress = null;
        PackageResponse response = api.getAllPackagesWithAuthedIPAndBasket(basketIdent, ipAddress);
        // TODO: test validations
    }

    /**
     * Get a basket
     *
     * Gets a basket associated with the provided identifier.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBasketTest() throws ApiException {
        String basketIdent = null;
        BasketResponse response = api.getBasket(basketIdent);
        // TODO: test validations
    }

    /**
     * Get auth links for basket
     *
     * Fetches a basket&#39;s auth URL. The player should be directed here in order for them to authorize their account. When complete, they will be returned to the provided &#x60;returnUrl&#x60; and the basket will be authorized from that moment onwards.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBasketAuthUrlTest() throws ApiException {
        String basketIdent = null;
        String returnUrl = null;
        List<BasketAuthResponseInner> response = api.getBasketAuthUrl(basketIdent, returnUrl);
        // TODO: test validations
    }

    /**
     * Get all categories
     *
     * Gets all categories from a webstore. This does not include package information. To include package information, add &#x60;?includePackages&#x3D;1&#x60; to the URL.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCategoriesTest() throws ApiException {
        CategoryResponse response = api.getCategories();
        // TODO: test validations
    }

    /**
     * Gets all categories and packages
     *
     * Gets all categories from a webstore including packages.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCategoriesIncludePackagesTest() throws ApiException {
        CategoryResponse response = api.getCategoriesIncludePackages();
        // TODO: test validations
    }

    /**
     * Get specific category
     *
     * Gets information about a category and returns the packages in that category.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCategoryTest() throws ApiException {
        String categoryId = null;
        SingleCategoryResponse response = api.getCategory(categoryId);
        // TODO: test validations
    }

    /**
     * Gets a specific category including packages, populating a dynamic category for the given basket.
     *
     * Gets information about a category and returns the packages in that category. When the category is dynamic and &#x60;basketIdent&#x60; is provided, the category is populated with the packages associated with that basket.  If a basket identifier is not provided, a dynamic category will be empty as the basket is required to relate packages to the category.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCategoryIncludeDynamicPackagesTest() throws ApiException {
        String categoryId = null;
        String basketIdent = null;
        SingleCategoryResponse response = api.getCategoryIncludeDynamicPackages(categoryId, basketIdent);
        // TODO: test validations
    }

    /**
     * Get a category with all packages
     *
     * Gets information about a category and returns the packages in that category.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCategoryIncludePackagesTest() throws ApiException {
        String categoryId = null;
        SingleCategoryResponse response = api.getCategoryIncludePackages(categoryId);
        // TODO: test validations
    }

    /**
     * Get custom pages defined for the webstore.
     *
     * Gets a list of custom pages associated with the webstore. These contain a &#x60;content&#x60; variable with the HTML content of the page.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomPagesTest() throws ApiException {
        CMSPagesResponse response = api.getCustomPages();
        // TODO: test validations
    }

    /**
     * Get Dynamic Categories
     *
     * Gets all categories from a webstore including packages. When &#x60;basketIdent&#x60; is provided, dynamic categories are populated with the packages associated with that basket.  If a basket identifier is not provided, dynamic categories will be empty as the basket is required to relate packages to the category.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDynamicCategoriesTest() throws ApiException {
        String basketIdent = null;
        CategoryResponse response = api.getDynamicCategories(basketIdent);
        // TODO: test validations
    }

    /**
     * Get package
     *
     * Gets a package from a webstore by its ID or slug.  Note: this endpoint does not support packages belonging to dynamic categories. Use the category endpoints with &#x60;includePackages&#x3D;1&#x60; and &#x60;basketIdent&#x60; to fetch dynamic packages.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPackageTest() throws ApiException {
        String packageId = null;
        SinglePackageResponse response = api.getPackage(packageId);
        // TODO: test validations
    }

    /**
     * Get packages available for basket
     *
     * Gets all packages available to the provided basket.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPackagesForBasketTest() throws ApiException {
        String basketIdent = null;
        PackageResponse response = api.getPackagesForBasket(basketIdent);
        // TODO: test validations
    }

    /**
     * Retrieves the available sidebar modules.
     *
     * Retrieves the available sidebar modules configured for the store.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSidebarTest() throws ApiException {
        String token = null;
        ModulesResponse response = api.getSidebar(token);
        // TODO: test validations
    }

    /**
     * Get user&#39;s tiered categories
     *
     * Gets all categories from the webstore, returning active tier information for the given player.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserTieredCategoriesTest() throws ApiException {
        Integer usernameId = null;
        CategoryResponse response = api.getUserTieredCategories(usernameId);
        // TODO: test validations
    }

    /**
     * Get the webstore&#39;s information
     *
     * Gets the webstore associated with the provided token
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWebstoreTest() throws ApiException {
        WebstoreResponse response = api.getWebstore();
        // TODO: test validations
    }

    /**
     * Remove a coupon from the basket.
     *
     * Removes a coupon code from a basket
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeCouponTest() throws ApiException {
        String basketIdent = null;
        ApplyCouponRequest applyCouponRequest = null;
        api.removeCoupon(basketIdent, applyCouponRequest);
        // TODO: test validations
    }

    /**
     * Removes the creator code from the basket.
     *
     * Removes the creator code from the basket.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeCreatorCodeTest() throws ApiException {
        String basketIdent = null;
        api.removeCreatorCode(basketIdent);
        // TODO: test validations
    }

    /**
     * Remove a gift card from the basket.
     *
     * Removes a gift card from the basket.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeGiftCardTest() throws ApiException {
        String basketIdent = null;
        RemoveGiftCardRequest removeGiftCardRequest = null;
        api.removeGiftCard(basketIdent, removeGiftCardRequest);
        // TODO: test validations
    }

    /**
     * Update user&#39;s tier to a new package
     *
     * Updates a tier to a new package. A recurring payment updated webhook is sent when an update is successful.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTierTest() throws ApiException {
        Integer tierId = null;
        UpdateTierRequest updateTierRequest = null;
        UpdateTierResponse response = api.updateTier(tierId, updateTierRequest);
        // TODO: test validations
    }

}
