/*
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.headless.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AddBasketPackageRequest
 */
public class AddBasketPackageRequestTest {
    private final AddBasketPackageRequest model = new AddBasketPackageRequest();

    /**
     * Model tests for AddBasketPackageRequest
     */
    @Test
    public void testAddBasketPackageRequest() {
        // TODO: test AddBasketPackageRequest
    }

    /**
     * Test the property 'packageId'
     */
    @Test
    public void packageIdTest() {
        // TODO: test packageId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'dynamic'
     */
    @Test
    public void dynamicTest() {
        // TODO: test dynamic
    }

}
