/*
 * Tebex Headless API
 * The headless API is designed for implementing your own store frontend with the data of your store. You are able to call the Headless API directly from a web browser (such as within an SPA), from a backend server, or in-game GUIs.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.headless.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tebex.headless.model.ModelPackage;
import io.tebex.headless.model.TierPendingDowngradePackage;
import io.tebex.headless.model.TierStatus;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Tier
 */
public class TierTest {
    private final Tier model = new Tier();

    /**
     * Model tests for Tier
     */
    @Test
    public void testTier() {
        // TODO: test Tier
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'usernameId'
     */
    @Test
    public void usernameIdTest() {
        // TODO: test usernameId
    }

    /**
     * Test the property '_package'
     */
    @Test
    public void _packageTest() {
        // TODO: test _package
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'recurringPaymentReference'
     */
    @Test
    public void recurringPaymentReferenceTest() {
        // TODO: test recurringPaymentReference
    }

    /**
     * Test the property 'nextPaymentDate'
     */
    @Test
    public void nextPaymentDateTest() {
        // TODO: test nextPaymentDate
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'pendingDowngradePackage'
     */
    @Test
    public void pendingDowngradePackageTest() {
        // TODO: test pendingDowngradePackage
    }

}
