/*
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.5
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.checkout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tebex.checkout.model.BasketRowMetaLimits;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BasketRowMeta
 */
public class BasketRowMetaTest {
    private final BasketRowMeta model = new BasketRowMeta();

    /**
     * Model tests for BasketRowMeta
     */
    @Test
    public void testBasketRowMeta() {
        // TODO: test BasketRowMeta
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rowprice'
     */
    @Test
    public void rowpriceTest() {
        // TODO: test rowprice
    }

    /**
     * Test the property 'initialprice'
     */
    @Test
    public void initialpriceTest() {
        // TODO: test initialprice
    }

    /**
     * Test the property 'isCumulative'
     */
    @Test
    public void isCumulativeTest() {
        // TODO: test isCumulative
    }

    /**
     * Test the property 'requiredPackages'
     */
    @Test
    public void requiredPackagesTest() {
        // TODO: test requiredPackages
    }

    /**
     * Test the property 'requiresAny'
     */
    @Test
    public void requiresAnyTest() {
        // TODO: test requiresAny
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'producesGiftCard'
     */
    @Test
    public void producesGiftCardTest() {
        // TODO: test producesGiftCard
    }

    /**
     * Test the property 'allowsGiftCards'
     */
    @Test
    public void allowsGiftCardsTest() {
        // TODO: test allowsGiftCards
    }

    /**
     * Test the property 'servers'
     */
    @Test
    public void serversTest() {
        // TODO: test servers
    }

    /**
     * Test the property 'limits'
     */
    @Test
    public void limitsTest() {
        // TODO: test limits
    }

    /**
     * Test the property 'hasDeliverables'
     */
    @Test
    public void hasDeliverablesTest() {
        // TODO: test hasDeliverables
    }

    /**
     * Test the property 'deliverableTypes'
     */
    @Test
    public void deliverableTypesTest() {
        // TODO: test deliverableTypes
    }

    /**
     * Test the property 'downloadLink'
     */
    @Test
    public void downloadLinkTest() {
        // TODO: test downloadLink
    }

    /**
     * Test the property 'hasSellerProtection'
     */
    @Test
    public void hasSellerProtectionTest() {
        // TODO: test hasSellerProtection
    }

    /**
     * Test the property 'itemType'
     */
    @Test
    public void itemTypeTest() {
        // TODO: test itemType
    }

    /**
     * Test the property 'revenueShare'
     */
    @Test
    public void revenueShareTest() {
        // TODO: test revenueShare
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'realprice'
     */
    @Test
    public void realpriceTest() {
        // TODO: test realprice
    }

}
