/*
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.5
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.checkout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tebex.checkout.model.PaymentCustomer;
import io.tebex.checkout.model.PaymentFees;
import io.tebex.checkout.model.PaymentPaymentMethod;
import io.tebex.checkout.model.PaymentPrice;
import io.tebex.checkout.model.PaymentProductsInner;
import io.tebex.checkout.model.PaymentStatus;
import io.tebex.checkout.model.RevenueShare;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Payment
 */
public class PaymentTest {
    private final Payment model = new Payment();

    /**
     * Model tests for Payment
     */
    @Test
    public void testPayment() {
        // TODO: test Payment
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'paymentSequence'
     */
    @Test
    public void paymentSequenceTest() {
        // TODO: test paymentSequence
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'pricePaid'
     */
    @Test
    public void pricePaidTest() {
        // TODO: test pricePaid
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'revenueShare'
     */
    @Test
    public void revenueShareTest() {
        // TODO: test revenueShare
    }

    /**
     * Test the property 'declineReason'
     */
    @Test
    public void declineReasonTest() {
        // TODO: test declineReason
    }

    /**
     * Test the property 'fees'
     */
    @Test
    public void feesTest() {
        // TODO: test fees
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'products'
     */
    @Test
    public void productsTest() {
        // TODO: test products
    }

    /**
     * Test the property 'coupons'
     */
    @Test
    public void couponsTest() {
        // TODO: test coupons
    }

    /**
     * Test the property 'giftCards'
     */
    @Test
    public void giftCardsTest() {
        // TODO: test giftCards
    }

    /**
     * Test the property 'recurringPaymentReference'
     */
    @Test
    public void recurringPaymentReferenceTest() {
        // TODO: test recurringPaymentReference
    }

    /**
     * Test the property 'custom'
     */
    @Test
    public void customTest() {
        // TODO: test custom
    }

}
