/*
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.5
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.checkout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.tebex.checkout.model.RecurringPaymentAmount;
import io.tebex.checkout.model.RecurringPaymentLinks;
import io.tebex.checkout.model.RecurringPaymentStatus;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RecurringPayment
 */
public class RecurringPaymentTest {
    private final RecurringPayment model = new RecurringPayment();

    /**
     * Model tests for RecurringPayment
     */
    @Test
    public void testRecurringPayment() {
        // TODO: test RecurringPayment
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'pausedAt'
     */
    @Test
    public void pausedAtTest() {
        // TODO: test pausedAt
    }

    /**
     * Test the property 'pausedUntil'
     */
    @Test
    public void pausedUntilTest() {
        // TODO: test pausedUntil
    }

    /**
     * Test the property 'nextPaymentDate'
     */
    @Test
    public void nextPaymentDateTest() {
        // TODO: test nextPaymentDate
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'interval'
     */
    @Test
    public void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'cancelledAt'
     */
    @Test
    public void cancelledAtTest() {
        // TODO: test cancelledAt
    }

    /**
     * Test the property 'cancellationRequestedAt'
     */
    @Test
    public void cancellationRequestedAtTest() {
        // TODO: test cancellationRequestedAt
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'cancelReason'
     */
    @Test
    public void cancelReasonTest() {
        // TODO: test cancelReason
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
