/*
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.5
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tebex.checkout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RecurringPaymentLinks
 */
public class RecurringPaymentLinksTest {
    private final RecurringPaymentLinks model = new RecurringPaymentLinks();

    /**
     * Model tests for RecurringPaymentLinks
     */
    @Test
    public void testRecurringPaymentLinks() {
        // TODO: test RecurringPaymentLinks
    }

    /**
     * Test the property 'initialPayment'
     */
    @Test
    public void initialPaymentTest() {
        // TODO: test initialPayment
    }

    /**
     * Test the property 'paymentHistory'
     */
    @Test
    public void paymentHistoryTest() {
        // TODO: test paymentHistory
    }

}
